services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      # 빌드된 JAR 파일 공유
      - ./build/libs:/app/build/libs
      # Firebase 키 공유
      - ./firebase-service-key.json:/app/firebase/firebase-service-key.json:ro
      # .env 파일 공유 (Spring이 직접 읽을 수 있도록)
      - ./.env:/app/.env:ro

volumes:
  db_data:
