spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/moneytogether?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

firebase:
  config-path: /app/firebase/firebase-service-key.json
  credentials:
    path: /app/firebase/firebase-service-key.json

#  credentials:
#    path: classpath:firebase/firebase-service-key.json

jwt:
  secret: ${JWT_SECRET}
  access-exp:  1209600000  # 14일   # 30분 1800000
  refresh-exp: 1209600000  # 14일

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

server:
  port: 8080
  address: 0.0.0.0


file:
  upload-dir: /Users/kimjieun/Desktop/upload/

