name: Deploy to AWS VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean bootJar -x test

      - name: List build/libs
        run: ls -l build/libs

      - name: Rename JAR
        run: |
          if ls build/libs/*.jar 1> /dev/null 2>&1; then
            mv build/libs/*.jar build/libs/app.jar
          else
            echo "No JAR found in build/libs!"
            exit 1
          fi

      - name: Copy files to AWS VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_VM_HOST }}
          username: ${{ secrets.AWS_VM_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: |
            build/libs/app.jar
            docker-compose.yml
          target: /home/ubuntu/moneytogether/

      - name: Upload ENV and Firebase key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_VM_HOST }}
          username: ${{ secrets.AWS_VM_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/moneytogether
            # 기존 파일 백업
            [ -f .env ] && mv .env .env.bak
            [ -f firebase-service-key.json ] && mv firebase-service-key.json firebase-service-key.json.bak
            # 새로운 파일 생성
            echo "${{ secrets.ENV_FILE }}" > .env
            echo "${{ secrets.FIREBASE_KEY }}" > firebase-service-key.json

      - name: Restart services with Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_VM_HOST }}
          username: ${{ secrets.AWS_VM_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/moneytogether
            docker compose down || true
            docker compose up -d --build
            docker compose ps
