name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Build with Gradle
      run: ./gradlew clean bootJar -x test

    - name: Copy files to AWS VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_VM_HOST }}
        username: ${{ secrets.AWS_VM_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        port: 22
        source: build/libs/moneytogether1-0.0.1-SNAPSHOT.jar,docker-compose.yml
        target: /home/ubuntu/moneytogether/

    - name: Run commands on AWS VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AWS_VM_HOST }}
        username: ${{ secrets.AWS_VM_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/moneytogether/
          docker compose down
          docker compose up -d --build
