name: Deploy MoneyTogether to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 4️⃣ JAR 이름에 커밋 SHA 포함
      - name: Rename JAR with commit SHA
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          mv build/libs/moneytogether1-0.0.1-SNAPSHOT.jar build/libs/moneytogether1-$COMMIT_SHA.jar
          echo "NEW_JAR=moneytogether1-$COMMIT_SHA.jar" >> $GITHUB_ENV

      # 5️⃣ VM에서 DB 컨테이너 먼저 띄우기
      - name: Start DB container on VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/moneytogether
            docker compose up -d db

      # 6️⃣ JAR 파일 VM으로 복사
      - name: Copy JAR to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "build/libs/${{ env.NEW_JAR }}"
          target: "/home/${{ secrets.VM_USER }}/moneytogether/"
          strip_components: 2

      # 7️⃣ 기존 애플리케이션 종료 후 새 JAR 실행
      - name: Restart application on VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            PID=$(ps aux | grep 'moneytogether1-.*\.jar' | grep -v grep | awk '{print $2}')
            if [ -n "$PID" ]; then
              kill -9 $PID
            fi
            cd /home/${{ secrets.VM_USER }}/moneytogether
            nohup java -jar ${{ env.NEW_JAR }} > moneytogether.log 2>&1 &
